language: ruby
before_install: rvm install 2.1.5 && rvm use 2.1.5
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
after_install: bundle exec rake db:setup

# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
notifications:
  slack: i-m-legend:PdvWPWK2bn9By9g6z3xBWFir


